livery = {
	{"Aircraft_02",	DIFFUSE			,	"Aircraft 02_BaseColor", false};
	{"Material.019",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Aircraft_01",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Canopy_Glass",	DIFFUSE			,	"F-117_glass", false};
	{"Bay_Left",	DIFFUSE			,	"Bay Left_BaseColor", false};
	{"Bay_Right",	DIFFUSE			,	"Bay Right_BaseColor", false};
	{"Bay_missiles",	DIFFUSE			,	"Bay missiles_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Bay_Front",	DIFFUSE			,	"Bay Front_BaseColor", false};
	{"Aircraft_01",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Aircraft_01",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.004",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.005",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Aircraft_01",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Aircraft_01.002",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Material.032",	DIFFUSE			,	"nighthawkgreen", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.029",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Material.002",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.010",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.013",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.014",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Material.018",	DIFFUSE			,	"Aircraft 01_BaseColor", false};
	{"Material.008",	DIFFUSE			,	"F-117_glass", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Cockpit_03.001",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_02.001",	DIFFUSE			,	"Cockpit 02_BaseColor", false};
	{"Cockpit_01",	DIFFUSE			,	"Cockpit 01_BaseColor", false};
	{"seat",	DIFFUSE			,	"seat_BaseColor", false};
	{"Hud",	DIFFUSE			,	"green", false};
	{"Cockpit_02",	DIFFUSE			,	"Cockpit 02_BaseColor", false};
	{"Material.001",	DIFFUSE			,	"black", false};
	{"Material.022",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.030",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.031",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.020",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.021",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.009",	DIFFUSE			,	"black", false};
	{"Material.011",	DIFFUSE			,	"black", false};
	{"Material.012",	DIFFUSE			,	"black", false};
	{"Material.023",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.024",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.025",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.026",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.027",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material.028",	DIFFUSE			,	"nighthawkgreen", false};
	{"Material",	DIFFUSE			,	"hgu55", false};
	{"Gear_front.001",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Bay_Front",	DIFFUSE			,	"Bay Front_BaseColor", false};
	{"Fuselage",	DIFFUSE			,	"white", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_front",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Material.015",	DIFFUSE			,	"Gear front_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Left",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Material.017",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Gear_Right",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Material.016",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"Cockpit_04",	DIFFUSE			,	"Cockpit 04_BaseColor", false};
	{"Gear_Left.001",	DIFFUSE			,	"Gear Left_BaseColor", false};
	{"Bay_Left",	DIFFUSE			,	"Bay Left_BaseColor", false};
	{"Bay_Left",	DIFFUSE			,	"Bay Left_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Door_Missiles_Left",	DIFFUSE			,	"Door Missiles Left_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Black",	DIFFUSE			,	"black", false};
	{"Black.001",	DIFFUSE			,	"White", false};
	{"Black.005",	DIFFUSE			,	"white", false};
	{"Black.008",	DIFFUSE			,	"white", false};
	{"Missile",	DIFFUSE			,	"Missile_BaseColor", false};
	{"Missile_Missile_Support_(2)",	DIFFUSE			,	"Missile_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Missile_Launcher",	DIFFUSE			,	"Missile Launcher_BaseColor", false};
	{"Material.007",	DIFFUSE			,	"F-117_Turbine", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"HGU-55.002",	DIFFUSE			,	"hgu55", false};
	{"HGU-55.002",	NORMAL_MAP			,	"hgu55_nm", false};
	{"PILOT_F22.002",	DIFFUSE			,	"Pilot_F117", false};
	{"PILOT_F22.002",	NORMAL_MAP			,	"Pilot_F117_nm", false};
	{"PILOT_F22.002",	DIFFUSE			,	"Pilot_F117", false};
	{"PILOT_F22.002",	NORMAL_MAP			,	"Pilot_F117_nm", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Gear_Right.001",	DIFFUSE			,	"Gear Right_BaseColor", false};
	{"Bay_Right",	DIFFUSE			,	"Bay Right_BaseColor", false};
	{"Bay_Right",	DIFFUSE			,	"Bay Right_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Door_Missiles_Right",	DIFFUSE			,	"Door Missiles Right_BaseColor", false};
	{"Aircraft_03",	DIFFUSE			,	"Aircraft 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
	{"Cockpit_03",	DIFFUSE			,	"Cockpit 03_BaseColor", false};
}
